# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: accfa297230a98d6c2e166a5323c2c9e9398e968a9da0ee18bd54769d5cc28e6384921f6a08eb9697da6ffc9fb1113f531c76325cab9089dc8f18b602f73505e

test:
  secret_key_base: 81ff4a1eb704c370b60095c3125286f683c48ae7dc8b5b815fa47ae636c402ad1e5d153a2a5e47296c8d5525a8cb77ff8cdb11aa4909a52063aa270a6d18e4e7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
